language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache: yarn
script:
  - yarn test
  - cd examples/example-event-handler
  - ../../graph.js codegen --output-dir src/types --debug
  - ../../graph.js build --debug
